## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
value_counts = application_df['CLASSIFICATION'].value_counts()
value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
greater_than_one = value_counts[value_counts > 1]
greater_than_one

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
equal_to_1 = value_counts[value_counts == 1]
equal_to_1

CLASSIFICATION
C2190    1
C4200    1
C2600    1
C5200    1
C1370    1
C1248    1
C6100    1
C1820    1
C1900    1
C1236    1
C3700    1
C2570    1
C1580    1
C1245    1
C2500    1
C1570    1
C1283    1
C2380    1
C1732    1
C1728    1
C2170    1
C4120    1
C8210    1
C2561    1
C4500    1
C2150    1
Name: count, dtype: int64

In [10]:
between_1_and_1000 = value_counts[(value_counts > 1) & (value_counts < 1000)]
between_1_and_1000

CLASSIFICATION
C7000    777
C1700    287
C4000    194
C5000    116
C1270    114
C2700    104
C2800     95
C7100     75
C1300     58
C1280     50
C1230     36
C1400     34
C7200     32
C2300     32
C1240     30
C8000     20
C7120     18
C1500     16
C1800     15
C6000     15
C1250     14
C8200     11
C1238     10
C1278     10
C1235      9
C1237      9
C7210      7
C2400      6
C1720      6
C4100      6
C1257      5
C1600      5
C1260      3
C2710      3
C0         3
C3200      2
C1234      2
C1246      2
C1267      2
C1256      2
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = ['C2190','C4200','C2600','C5200','C1370','C1248','C6100','C1820','C1900','C1236','C3700','C2570','C1580','C1245','C2500','C1570','C1283','C2380','C1732','C1728','C2170','C4120','C8210','C2561','C4500','C2150', 'C7000', 'C1700'
,'C4000'
,'C5000'
,'C1270'
,'C2700'
,'C2800'
,'C7100'
,'C1300'
,'C1280'
,'C1230'
,'C1400'
,'C7200'
,'C2300'
,'C1240'
,'C8000'
,'C7120'
,'C1500'
,'C1800'
,'C6000'
,'C1250'
,'C8200'
,'C1238'
,'C1278'
,'C1235'
,'C1237'
,'C7210'
,'C2400'
,'C1720'
,'C4100'
,'C1257'
,'C1600'
,'C1260'
,'C2710'
,'C0'
,'C3200'
,'C1234'
,'C1246'
,'C1267'
,'C1256']

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [12]:
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,True,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,True,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,True,...,False,False,True,False,False,False,False,False,True,False

In [14]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"]
X = application_df.drop(columns='IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [16]:
len(X_train.columns)

47

## Compile, Train and Evaluate the Model

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train.columns)
input_nodes_1 = 80
input_nodes_2 = 40
input_nodes_3 = 20

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units= input_nodes_1, input_dim= number_input_features, activation= 'relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units= input_nodes_2, activation= 'relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units= input_nodes_3, activation= 'relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units= 1, activation= 'sigmoid'))

# Check the structure of the model
nn.summary()

/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 80)             │         3,840 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 40)             │         3,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 20)             │           820 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,921 (30.94 KB)

 Trainable params: 7,921 (30.94 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics= ['accuracy'])

In [19]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs= 100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 430us/step - accuracy: 0.7051 - loss: 0.5953
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.7300 - loss: 0.5559
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - accuracy: 0.7333 - loss: 0.5507
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.7282 - loss: 0.5544
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.7333 - loss: 0.5508
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - accuracy: 0.7353 - loss: 0.5457
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - accuracy: 0.7377 - loss: 0.5440
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - accuracy: 0.7345 - loss: 0.5472
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.7367 - loss: 0.5456
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.7362 - loss: 0.5410
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 396us/step - accuracy: 0.7329 - loss: 0.5468
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - accuracy: 0.7401 - loss: 0.5391
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - accuracy: 0.7324 - loss: 0.5471
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.7337 - loss: 0.5465
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - accuracy: 0.7373 - loss: 0.5405
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 400us/step - accuracy: 0.7350 - loss: 0.5427
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - accuracy: 0.7356 - loss: 0.5438
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.7332 - loss: 0.5461
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - accuracy: 0.7337 - loss: 0.5438
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.7347 - loss: 0.5447
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - accuracy: 0.7383 - loss: 0.5401
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - accuracy: 0.7397 - loss: 0.5393
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - accuracy: 0.7352 - loss: 0.5440
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.7361 - loss: 0.5414
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - accuracy: 0.7376 - loss: 0.5387
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - accuracy: 0.7413 - loss: 0.5358
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.7377 - loss: 0.5382
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - accuracy: 0.7368 - loss: 0.5408
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 395us/step - accuracy: 0.7365 - loss: 0.5402
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - accuracy: 0.7422 - loss: 0.5335
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.7386 - loss: 0.5367
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - accuracy: 0.7412 - loss: 0.5347
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - accuracy: 0.7372 - loss: 0.5416
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.7381 - loss: 0.5386
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 658us/step - accuracy: 0.7339 - loss: 0.5421
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.7368 - loss: 0.5396
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.7353 - loss: 0.5421
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - accuracy: 0.7449 - loss: 0.5311
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.7406 - loss: 0.5380
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.7394 - loss: 0.5337
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - accuracy: 0.7369 - loss: 0.5383
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.7418 - loss: 0.5377
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - accuracy: 0.7394 - loss: 0.5365
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.7423 - loss: 0.5358
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7387 - loss: 0.5357
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.7409 - loss: 0.5358
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.7428 - loss: 0.5317
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7417 - loss: 0.5344
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.7425 - loss: 0.5331
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.7395 - loss: 0.5326
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7424 - loss: 0.5333
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - accuracy: 0.7393 - loss: 0.5383
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.7387 - loss: 0.5363
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7424 - loss: 0.5352
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.7390 - loss: 0.5370
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7401 - loss: 0.5365
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.7399 - loss: 0.5366
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.7431 - loss: 0.5336
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.7333 - loss: 0.5402
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7380 - loss: 0.5376
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - accuracy: 0.7379 - loss: 0.5347
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.7469 - loss: 0.5293
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.7381 - loss: 0.5370
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7416 - loss: 0.5320
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7386 - loss: 0.5376
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - accuracy: 0.7417 - loss: 0.5328
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.7387 - loss: 0.5359
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 469us/step - accuracy: 0.7413 - loss: 0.5339
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7426 - loss: 0.5317
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.7376 - loss: 0.5352
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7389 - loss: 0.5358
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 470us/step - accuracy: 0.7406 - loss: 0.5361
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 695us/step - accuracy: 0.7438 - loss: 0.5297
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - accuracy: 0.7416 - loss: 0.5349
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.7357 - loss: 0.5397
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - accuracy: 0.7375 - loss: 0.5363
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.7404 - loss: 0.5360
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.7438 - loss: 0.5333
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.7399 - loss: 0.5326
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.7413 - loss: 0.5340
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.7398 - loss: 0.5350
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step - accuracy: 0.7368 - loss: 0.5349
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - accuracy: 0.7394 - loss: 0.5339
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step - accuracy: 0.7421 - loss: 0.5319
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - accuracy: 0.7368 - loss: 0.5361
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step - accuracy: 0.7378 - loss: 0.5362
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - accuracy: 0.7403 - loss: 0.5341
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.7419 - loss: 0.5325
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step - accuracy: 0.7408 - loss: 0.5305
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.7383 - loss: 0.5364
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.7419 - loss: 0.5327
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - accuracy: 0.7440 - loss: 0.5330
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 507us/step - accuracy: 0.7448 - loss: 0.5274
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - accuracy: 0.7408 - loss: 0.5339
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.7438 - loss: 0.5334
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.7429 - loss: 0.5325
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.7428 - loss: 0.5299
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.7403 - loss: 0.5323
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - accuracy: 0.7438 - loss: 0.5287
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - accuracy: 0.7441 - loss: 0.5294

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 614us/step - accuracy: 0.7286 - loss: 0.5684
Loss: 0.568390429019928, Accuracy: 0.7286297082901001

In [21]:
# Export our model to HDF5 file
nn.save('Models/AlphabetSoupCharity_Optimization_1.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.