## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
application_df.nunique()

EIN                       34299
NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [3]:
application_df['NAME'].head(50)

0                          BLUE KNIGHTS MOTORCYCLE CLUB
1                AMERICAN CHESAPEAKE CLUB CHARITABLE TR
2                    ST CLOUD PROFESSIONAL FIREFIGHTERS
3                        SOUTHSIDE ATHLETIC ASSOCIATION
4              GENETIC RESEARCH INSTITUTE OF THE DESERT
5     MINORITY ORGAN & TISSUE TRANSPLANT & EDUCATION...
6     FRIENDS OF ARTS COUNCIL OF GREATER DENHAM SPRI...
7                             ISRAEL EMERGENCY ALLIANCE
8                                      ARAMCO BRATS INC
9            INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS
10                        KAI ELUA OUTRIGGER CANOE CLUB
11                                     HERITAGE ACADEMY
12                     THE UNITED STATES PONY CLUBS INC
13    DOMINION INTERNATIONAL NETWORK OF MINISTRIES &...
14                                     V O W FOUNDATION
15                       JOSEPH E PEEBLES JR FOUNDATION
16    WASHINGTON ASSOCIATION OF PHYSICIANS OF INDIAN...
17                     SAINT FRANCIS HOSPITAL SOUTH LLC
18           ANCHORAGE COMMUNITY MENTAL HEALTH SERVICES
19               HABITAT FOR HUMANITY INTERNATIONAL INC
20                        INTERNATIONAL FELINE SHOWCASE
21                     METAMORPHASIS POWERHOUSE COMPANY
22                             REACH FOR EXCELLENCE INC
23              INTERNATIONAL ASSOCIATION OF LIONS CLUB
24                     SONS OF CONFEDERATE VETERANS INC
25             MAGDALENA OLD TIMERS REUNION ASSOCIATION
26              INFRAGARD NATIONAL MEMBERS ALLIANCE INC
27                       POP WARNER LITTLE SCHOLARS INC
28          FLORIDA STATE UNIVERSITY ALUMNI ASSOCIATION
29         HAWAII TRAVEL & TOURISM RESEARCH ASSOCIATION
30    MEDICAL STAFF OF PARKVIEW COMMUNITY HOSPITAL M...
31                                   CLEAR UP SKIN CARE
32       STAR TOURING AND RIDING SACARMENTO CHAPTER 153
33        SHERIFFS COMMUNITY ORGANIZED POLICING EFFORTS
34                 DOCTORS OFFERING CHARITABLE SERVICES
35                                     G A P MINISTRIES
36                             MELLOWTONES BIG BAND INC
37    SAI HUMANITARIAN INSTITUTE OF LEARNING AND HEA...
38                                          RIVERVIEW 2
39                    ERASTO R BATONGMALAQUE FOUNDATION
40                  TIFTON JUDICIAL CIRCUIT SHELTER INC
41                       IBEW LOCAL 180 HOLDING COMPANY
42          ORLANDO PARROT HEADS OF CENTRAL FLORIDA INC
43               HABITAT FOR HUMANITY INTERNATIONAL INC
44                 HOLY SPIRIT CHURCH AND INSTITUTE INC
45             K-9 SEARCH AND RESCUE OF ORANGE CITY INC
46                                   PTA TEXAS CONGRESS
47             SOUTHERN CALIFORNIA NATURIST ASSOCIATION
48                                MOSES SONG MINISTRIES
49                      VINCI PARK HOME AND SCHOOL CLUB
Name: NAME, dtype: object

In [4]:
# Separate names into various categories based on the organization mame
application_df['NAME_CATEGORY'] = application_df['NAME'].apply(lambda x:
                                                      'Club' if 'club' in x.lower() else
                                                      'Association' if 'association' in x.lower() else
                                                      'Foundation' if 'foundation' in x.lower() else
                                                      'Company' if 'company' in x.lower() else
                                                      'LLC' if 'llc' in x.lower() else
                                                      'Inc' if 'inc' in x.lower() else
                                                      'University' if 'university' in x.lower() else
                                                      'International' if 'international' in x.lower() else
                                                      'Non-profit' if 'non-profit' in x.lower() else
                                                      'Corporation' if 'corporation' in x.lower() else
                                                      'Trust' if 'trust' in x.lower() else
                                                      'Other')

In [5]:
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,NAME_CATEGORY
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1,Club
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1,Club
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0,Other
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1,Association
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1,Other

In [6]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,NAME_CATEGORY
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1,Club
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1,Club
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0,Other
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1,Association
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1,Other

In [7]:
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
 10  NAME_CATEGORY           34299 non-null  object
dtypes: int64(3), object(8)
memory usage: 2.9+ MB

In [8]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
NAME_CATEGORY               12
dtype: int64

In [9]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [10]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: count, dtype: int64

In [11]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
value_counts = application_df['CLASSIFICATION'].value_counts()
value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [12]:
# You may find it helpful to look at CLASSIFICATION value counts >1
greater_than_one = value_counts[value_counts > 1]
greater_than_one

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [13]:
equal_to_1 = value_counts[value_counts == 1]
equal_to_1

CLASSIFICATION
C2190    1
C4200    1
C2600    1
C5200    1
C1370    1
C1248    1
C6100    1
C1820    1
C1900    1
C1236    1
C3700    1
C2570    1
C1580    1
C1245    1
C2500    1
C1570    1
C1283    1
C2380    1
C1732    1
C1728    1
C2170    1
C4120    1
C8210    1
C2561    1
C4500    1
C2150    1
Name: count, dtype: int64

In [14]:
between_1_and_1000 = value_counts[(value_counts > 1) & (value_counts < 1000)]
between_1_and_1000

CLASSIFICATION
C7000    777
C1700    287
C4000    194
C5000    116
C1270    114
C2700    104
C2800     95
C7100     75
C1300     58
C1280     50
C1230     36
C1400     34
C7200     32
C2300     32
C1240     30
C8000     20
C7120     18
C1500     16
C1800     15
C6000     15
C1250     14
C8200     11
C1238     10
C1278     10
C1235      9
C1237      9
C7210      7
C2400      6
C1720      6
C4100      6
C1257      5
C1600      5
C1260      3
C2710      3
C0         3
C3200      2
C1234      2
C1246      2
C1267      2
C1256      2
Name: count, dtype: int64

In [15]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = ['C2190','C4200','C2600','C5200','C1370','C1248','C6100','C1820','C1900','C1236','C3700','C2570','C1580','C1245','C2500','C1570','C1283','C2380','C1732','C1728','C2170','C4120','C8210','C2561','C4500','C2150', 'C7000', 'C1700'
,'C4000'
,'C5000'
,'C1270'
,'C2700'
,'C2800'
,'C7100'
,'C1300'
,'C1280'
,'C1230'
,'C1400'
,'C7200'
,'C2300'
,'C1240'
,'C8000'
,'C7120'
,'C1500'
,'C1800'
,'C6000'
,'C1250'
,'C8200'
,'C1238'
,'C1278'
,'C1235'
,'C1237'
,'C7210'
,'C2400'
,'C1720'
,'C4100'
,'C1257'
,'C1600'
,'C1260'
,'C2710'
,'C0'
,'C3200'
,'C1234'
,'C1246'
,'C1267'
,'C1256']

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [16]:
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
 10  NAME_CATEGORY           34299 non-null  object
dtypes: int64(3), object(8)
memory usage: 2.9+ MB

In [17]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,...,NAME_CATEGORY_Company,NAME_CATEGORY_Corporation,NAME_CATEGORY_Foundation,NAME_CATEGORY_Inc,NAME_CATEGORY_International,NAME_CATEGORY_LLC,NAME_CATEGORY_Non-profit,NAME_CATEGORY_Other,NAME_CATEGORY_Trust,NAME_CATEGORY_University
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,108590,1,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,1,6692,1,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,1,142590,1,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False

In [18]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"]
X = application_df.drop(columns='IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [19]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [20]:
len(X_train.columns)

59

## Compile, Train and Evaluate the Model

In [21]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train.columns)
input_nodes_1 = 80
input_nodes_2 = 40

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units= input_nodes_1, input_dim= number_input_features, activation= 'relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units= input_nodes_2, activation= 'relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units= 1, activation= 'sigmoid'))

# Check the structure of the model
nn.summary()

/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 80)             │         4,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 40)             │         3,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            41 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,081 (31.57 KB)

 Trainable params: 8,081 (31.57 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics= ['accuracy'])

In [23]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs= 100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 558us/step - accuracy: 0.7134 - loss: 0.5766
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 469us/step - accuracy: 0.7576 - loss: 0.5166
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.7582 - loss: 0.5108
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - accuracy: 0.7584 - loss: 0.5113
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - accuracy: 0.7562 - loss: 0.5165
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.7610 - loss: 0.5114
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - accuracy: 0.7684 - loss: 0.5026
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.7663 - loss: 0.5009
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step - accuracy: 0.7645 - loss: 0.5025
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - accuracy: 0.7632 - loss: 0.5027
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - accuracy: 0.7626 - loss: 0.5039
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.7661 - loss: 0.4969
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.7632 - loss: 0.5011
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.7643 - loss: 0.4962
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.7725 - loss: 0.4906
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step - accuracy: 0.7696 - loss: 0.4923
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 469us/step - accuracy: 0.7670 - loss: 0.4962
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step - accuracy: 0.7666 - loss: 0.4954
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.7674 - loss: 0.4957
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7699 - loss: 0.4926
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.7716 - loss: 0.4957
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.7691 - loss: 0.4940
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.7674 - loss: 0.4949
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7674 - loss: 0.4942
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.7705 - loss: 0.4906
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.7691 - loss: 0.4923
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step - accuracy: 0.7706 - loss: 0.4884
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7682 - loss: 0.4906
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - accuracy: 0.7757 - loss: 0.4816
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 401us/step - accuracy: 0.7754 - loss: 0.4871
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7750 - loss: 0.4891
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7731 - loss: 0.4843
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7773 - loss: 0.4819
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7754 - loss: 0.4843
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7740 - loss: 0.4852
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.7773 - loss: 0.4796
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - accuracy: 0.7730 - loss: 0.4854
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7722 - loss: 0.4884
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 401us/step - accuracy: 0.7757 - loss: 0.4836
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 398us/step - accuracy: 0.7715 - loss: 0.4880
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - accuracy: 0.7747 - loss: 0.4816
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7714 - loss: 0.4857
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7767 - loss: 0.4849
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.7719 - loss: 0.4831
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7766 - loss: 0.4808
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7821 - loss: 0.4760
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7773 - loss: 0.4785
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.7754 - loss: 0.4816
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.7801 - loss: 0.4776
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7740 - loss: 0.4851
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.7770 - loss: 0.4797
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7766 - loss: 0.4818
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.7790 - loss: 0.4759
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7786 - loss: 0.4779
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step - accuracy: 0.7752 - loss: 0.4810
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.7753 - loss: 0.4824
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.7798 - loss: 0.4771
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7751 - loss: 0.4810
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7763 - loss: 0.4769
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7780 - loss: 0.4791
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.7716 - loss: 0.4871
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.7725 - loss: 0.4833
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7757 - loss: 0.4843
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.7782 - loss: 0.4788
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 400us/step - accuracy: 0.7760 - loss: 0.4802
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 395us/step - accuracy: 0.7789 - loss: 0.4759
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - accuracy: 0.7762 - loss: 0.4809
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.7751 - loss: 0.4799
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - accuracy: 0.7766 - loss: 0.4801
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - accuracy: 0.7741 - loss: 0.4778
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - accuracy: 0.7763 - loss: 0.4792
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - accuracy: 0.7762 - loss: 0.4798
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - accuracy: 0.7803 - loss: 0.4744
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7763 - loss: 0.4806
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7774 - loss: 0.4782
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7782 - loss: 0.4790
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7781 - loss: 0.4748
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7749 - loss: 0.4799
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 368us/step - accuracy: 0.7789 - loss: 0.4756
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7767 - loss: 0.4762
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7764 - loss: 0.4776
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - accuracy: 0.7777 - loss: 0.4776
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - accuracy: 0.7796 - loss: 0.4725
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - accuracy: 0.7765 - loss: 0.4766
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - accuracy: 0.7784 - loss: 0.4781
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - accuracy: 0.7742 - loss: 0.4773
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7753 - loss: 0.4819
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7764 - loss: 0.4762
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7766 - loss: 0.4788
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7758 - loss: 0.4826
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - accuracy: 0.7786 - loss: 0.4783
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - accuracy: 0.7768 - loss: 0.4772
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7733 - loss: 0.4797
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - accuracy: 0.7766 - loss: 0.4751
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7791 - loss: 0.4720
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - accuracy: 0.7792 - loss: 0.4758
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 371us/step - accuracy: 0.7729 - loss: 0.4824
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7734 - loss: 0.4785
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 341us/step - accuracy: 0.7781 - loss: 0.4745
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7794 - loss: 0.4719

In [24]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 467us/step - accuracy: 0.7546 - loss: 0.5323
Loss: 0.5323020219802856, Accuracy: 0.7546355724334717

In [25]:
# Export our model to HDF5 file
nn.save('Models/AlphabetSoupCharity_Optimization_3.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.